# Generated by Django 3.2.7 on 2021-09-10 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
